import {
  Artimage,
  Belmont,
  BVron,
  CalamityNolan,
  Kaeon,
  Kyleanderror,
  LostLake,
  MysteryDip,
  Tim,
  DarkSouls,
  DarkSouls2,
  FF9,
  MegaManX,
  MegaMan2,
  Metroid,
  FarCry2,
  DevilMayCry,
  GTA3,
  REVillage,
  Rogue,
  SMB,
  XCom,
  Zelda,
  Contra,
  Branding
} from "./images";

export const STREAMERS = [
  {
    desc: "A gamer and mental health advocate looking to use one in efforts of helping with the other.",
    game: {
      art: FF9,
      developer: "Square Electronic Arts",
      title: "Final Fantasy IX",
      year: "2000",
    },
    image: Artimage,
    link: "https://www.twitch.tv/artimage84",
    name: "Artimage",
    handle: "artimage84",
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "Belmont is working his way through a shameful backlog.",
    link: "https://www.twitch.tv/rirchterbelmont",
    name: "Belmont",
    handle: "rirchterbelmont",
    game: {
      art: MegaManX,
      developer: "Capcom",
      title: "Mega Man X",
      year: "1993",
    },
    image: Belmont,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "bvronmusic streams Games + Demos.",
    link: "https://www.twitch.tv/bvronmusic",
    name: "BVron",
    handle: "bvronmusic",
    game: {
      art: GTA3,
      developer: "Rockstar",
      title: "Grand Theft Auto III",
      year: "2001",
    },
    image: BVron,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "Variety streams, speedruns, critical plays and fundraising!",
    link: "https://www.twitch.tv/calamitynolan",
    name: "CalamityNolan",
    handle: "calamitynolan",
    game: {
      art: DevilMayCry,
      developer: "Capcom",
      title: "Devil May Cry, Resident Evil Village",
      year: "2001",
    },
    image: CalamityNolan,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "I'm on the quest to beat every Nintendo Entertainment System game released in North America.",
    link: "https://www.twitch.tv/kaeon",
    name: "Kaeon",
    name: "kaeon",
    game: {
      art: MegaMan2,
      developer: "Capcom",
      title: "Mega Man 2, The Legend of Zelda, Super Mario Bros.",
      year: "1988",
    },
    image: Kaeon,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "I like playing games and I like talking to people about games. So... why not both?",
    link: "https://www.twitch.tv/kyleanderror13",
    name: "kyleanderror13",
    handle: "kyleanderror13",
    game: {
      art: DarkSouls,
      developer: "FromSoftware",
      title: "Dark Souls",
      year: "2011",
    },
    image: Kyleanderror,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "I'm an old man who's bad at the video games. But lets try playing and talking at the same time!",
    link: "https://www.twitch.tv/lostlake86",
    name: "LostLake86",
    handle: "lostlake86",
    game: {
      art: FarCry2,
      developer: "Ubisoft",
      title: "Far Cry 2",
      year: "2008",
    },
    image: LostLake,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "Seeking a greater understanding of the gamedev craft, one game at a time",
    link: "https://www.twitch.tv/mystery_dip",
    name: "mystery_dip",
    handle: "mystery_dip",
    game: {
      art: Rogue,
      developer: "A.I. Design",
      title: "Rogue",
      year: "1980",
    },
    image: MysteryDip,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
  {
    desc: "Dev Game Club co-host and old man who makes games. Ex-Creative Director on franchises like Star Wars, Halo, and Tomb Raider. Halo 5/Ex-Infinite, Star Wars Republic Commando, Ex-Tomb Raider (Reboot) among others. Co-founder Twin Suns Corp.",
    link: "https://www.twitch.tv/timlongojr",
    name: "timlongojr",
    handle: "timelongjr",
    game: { art: XCom, developer: "MythosGames", title: "XCOM", year: "1994" },
    image: Tim,
    day: "Saturday, January 27, 2024",
    start_time: "12:00 pm",
    end_time: "11:00 pm",
  },
];

export const SCHEDULE = [{
    channel: "artimage84",
    name: "Artimage",
    game: {
      art: Branding,
      developer: "",
      title: "Defeating Games Pre-show",
      year: "",
    },
    link: "https://www.twitch.tv/artimage84",
    image: Artimage,
    day: "January 27, 2024",
    start_time: 1130 - 100,
    end_time: 1200 - 100,
  },
  {
    channel: "artimage84",
    name: "Artimage",
    game: {
      art: FF9,
      developer: "Square Electronic Arts",
      title: "Final Fantasy IX",
      year: "2000",
    },
    link: "https://www.twitch.tv/artimage84",
    image: Artimage,
    day: "January 27, 2024",
    start_time: 1200 - 100,
    end_time: 1400 - 100,
  },
  {
    channel: "lostlake86",
    name: "LostLake86",
    game: {
      art: FarCry2,
      developer: "Ubisoft",
      title: "Far Cry 2",
      year: "2008",
    },
    link: "https://www.twitch.tv/lostlake86",
    image: LostLake,
    day: "January 27, 2024",
    start_time: 1400 - 100,
    end_time: 1630 - 100,
  },
  {
    channel: "calamitynolan",
    name: "CalamityNolan",
    game: {
      art: DevilMayCry,
      developer: "Capcom",
      title: "Devil May Cry",
      year: "2001",
    },
    link: "https://www.twitch.tv/calamitynolan",
    image: CalamityNolan,
    day: "January 27, 2024",
    start_time: 1630 - 100,
    end_time: 1930 - 100,
  },
  {
    channel: "kaeon",
    name: "Kaeon",
    game: {
      art: MegaMan2,
      developer: "Capcom, Nintendo, Nintendo",
      title: "Mega Man 2, The Legend of Zelda, Super Mario Bros.",
      year: "1988, 1986, 1985",
    },
    link: "https://www.twitch.tv/kaeon",
    image: Kaeon,
    day: "January 27, 2024",
    start_time: 1930 - 100,
    end_time: 2200 - 100,
  },
  {
    channel: "kyleanderror13",
    name: "kyleanderror13",
    game: {
      art: DarkSouls,
      developer: "FromSoftware",
      title: "Dark Souls",
      year: "2011",
    },
    link: "https://www.twitch.tv/kyleanderror13",
    image: Kyleanderror,
    day: "January 27, 2024",
    start_time: 2200 - 100,
    end_time: 2400 - 100,
  },
  {
    channel: "artimage84",
    name: "Artimage",
    game: {
      art: FF9,
      developer: "Square Electronic Arts",
      title: "Final Fantasy IX",
      year: "2000",
    },
    link: "https://www.twitch.tv/artimage84",
    image: Artimage,
    day: "January 28, 2024",
    start_time: 100 - 100,
    end_time: 700 - 100,
  },
  {
    channel: "kyleanderror13",
    name: "kyleanderror13",
    game: {
      art: DarkSouls2,
      developer: "FromSoftware",
      title: "Dark Souls II",
      year: "2014",
    },
    link: "https://www.twitch.tv/kyleanderror13",
    image: Kyleanderror,
    day: "January 28, 2024",
    start_time: 700 - 100,
    end_time: 1000 - 100,
  },
  {
    channel: "artimage84",
    name: "Artimage",
    game: {
      art: FF9,
      developer: "Square Electronic Arts",
      title: "Final Fantasy IX",
      year: "2000",
    },
    link: "https://www.twitch.tv/artimage84",
    image: Artimage,
    day: "January 28, 2024",
    start_time: 1000 - 100,
    end_time: 1200 - 100,
  },
  {
    channel: "bvronmusic",
    name: "BVron",
    game: {
      art: GTA3,
      developer: "Rockstar",
      title: "Grand Theft Auto III",
      year: "2001",
    },
    link: "https://www.twitch.tv/bvronmusic",
    image: BVron,
    day: "January 28, 2024",
    start_time: 1200 - 100,
    end_time: 1330 - 100,
  },
  {
    channel: "lostlake86",
    name: "MysteryDip via LostLake86",
    game: {
      art: Rogue,
      developer: "A.I. Design",
      title: "Rogue",
      year: "1980",
    },
    link: "https://www.twitch.tv/lostlake86",
    image: MysteryDip,
    day: "January 28, 2024",
    start_time: 1330 - 100,
    end_time: 1530 - 100,
  },
  {
    channel: "timlongojr",
    name: "timlongojr",
    game: {
      art: XCom,
      developer: "MythosGames",
      title: "XCOM",
      year: "1994",
    },
    link: "https://www.twitch.tv/timlongojr",
    image: Tim,
    day: "January 28, 2024",
    start_time: 1530 - 100,
    end_time: 1730 - 100,
  },
  {
    channel: "rirchterbelmont",
    name: "Belmont",
    game: {
      art: MegaManX,
      developer: "Capcom",
      title: "Mega Man X",
      year: "1993",
    },
    link: "https://www.twitch.tv/rirchterbelmont",
    image: Belmont,
    day: "January 28, 2024",
    start_time: 1730 - 100,
    end_time: 1900 - 100,
  },
  {
    channel: "calamitynolan",
    name: "CalamityNolan",
    game: {
      art: REVillage,
      developer: "Capcom",
      title: "Resident Evil: Village",
      year: "2021",
    },
    link: "https://www.twitch.tv/calamitynolan",
    image: CalamityNolan,
    day: "January 28, 2024",
    start_time: 1900 - 100,
    end_time: 2200 - 100,
  },
  {
    channel: "kaeon",
    name: "Kaeon",
    game: {
      art: Metroid,
      developer: "Nintendo",
      title: "Metroid",
      year: "1986",
    },
    link: "https://www.twitch.tv/kaeon",
    image: Kaeon,
    day: "January 28, 2024",
    start_time: 2200 - 100,
    end_time: 2300 - 100,
    stretch_goal: {
        target: 2000
    },
  },
  {
    channel: "kaeon",
    name: "Kaeon",
    game: {
      art: Contra,
      developer: "Konami",
      title: "Contra",
      year: "1988",
    },
    link: "https://www.twitch.tv/kaeon",
    image: Kaeon,
    day: "January 28, 2024",
    start_time: 2300 - 100,
    end_time: 2330 - 100,
    stretch_goal: {
        target: 2500
    },
  },
];
